from icalendar import Calendar, Event
from datetime import datetime
import pytz


def gen_time(year,month,day,hour,minu):
    return datetime(year, month, day, hour, minu, tzinfo=pytz.timezone('Asia/Kolkata'))

UNTIL = gen_time(2017, 11, 30, 23, 59)
OUTFILE = 'timetable.ics'

cal = Calendar()
cal.add('prodid', '-//IT IS GENERATED BY ADITYA PRATAP SINGH//')
cal.add('version', '1.0')


def generate_event(summary,description,start,end,location,freq):
    event = Event()
    event.add('summary', summary)
    event.add('description', description)
    event.add('dtstart', start)
    event.add('dtend', end)
    event.add('location',location)
    event.add('rrule', { 'FREQ': freq, 'UNTIL':UNTIL})
    return event


if __name__ == '__main__':
    
    event = Event()

    summary='Congratulation to add python timetable.'
    description= 'Programmer can do anything.'
    location = 'Your Home'

    build_event = generate_event(summary,description,gen_time(2017, 10, 1, 10, 0),gen_time(2017, 10, 1, 12, 0),location,"WEEKLY")
    cal.add_component(build_event)    

    f = open(OUTFILE, 'wb')
    f.write(cal.to_ical())
    f.close()        
    print("NOTICE: Your timetable is written to %s" % OUTFILE)


 
